// <auto-generated />
namespace MastersDetailsInMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class f3434 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(f3434));
        
        string IMigrationMetadata.Id
        {
            get { return "202403050605047_f3434"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
